### ISSUE TITLE
Incorrect transformation when there are conditional mutations 

### ISSUE THREAD

**Issue by nktpro** [babel-plugins/babel-plugin-react-constant-elements#1]
The transformer breaks in this simple test case:

    class Node extends React.Component {
      render() {
        let children = <b></b>;

        if (someCondition) {
          children = <span></span>;
        }

        return <div>{children}</div>;
      }
    }

which compiles to

    var _ref = React.createElement("b", null);
    var _ref2 = React.createElement("span", null);
    var _ref3 = React.createElement(
      "div",
      null,
      children
    );

    var Node = (function (_React$Component) {
      function Node() {
        _classCallCheck(this, Node);

        _React$Component.apply(this, arguments);
      }

      _inherits(Node, _React$Component);

      Node.prototype.render = function render() {
        var children = _ref;

        if (someCondition) {
          children = _ref2;
        }

        return _ref3;
      };

      return Node;
    })(React.Component);

Notice that _ref3 is incorrectly determined as immutable and `children` is carried out of scope, which leads to a runtime error.

**Comment by nktpro** [comment]
Here's another case that leads to bad optimization:

    function renderSome(a, b) {
      if (a) {
        return <div>{b}</div>
      }
      else {
        return <span>{b}</span>
      }
    }

Compiles to:

    function renderSome(a, b) {
      var _ref2 = React.createElement(
        "span",
        null,
        b
      );
    
      var _ref = React.createElement(
        "div",
        null,
        b
      );
    
      if (a) {
        return _ref;
      } else {
        return _ref2;
      }
    }
    
which makes it worse since all elements are created up front regardless of the conditions.

**Comment by sebmck** [comment]
> Notice that _ref3 is incorrectly determined as immutable

Nope, we actually hoist mutable elements as high as they can too, see facebook/react#3226 for more info on how it should/actually works.

**Comment by nktpro** [comment]
I think you overlooked this case, _ref3 can't be hoisted outside of `render()` because of `children`. It's a runtime error.

**Comment by sebmck** [comment]
I know. I was just commenting on your immutability comment.

On Wednesday, 8 July 2015, nktpro <notifications@github.com> wrote:

> I think you overlooked this case, _ref3 can't be hoisted outside of
> render() because of children. It's a runtime error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel-plugins/babel-plugin-react-constant-elements/issues/1#issuecomment-119510002>
> .
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
The `children` binding is being identified as a constant and so it's constant violation paths are being pushed and they're never being hit when invalidation is being checked.

**Comment by nktpro** [comment]
@sebmck Just a quick update: this transformer is now perfect after this fix. I could finally used it in a huge production app (25K LoC, 1MB minified of just custom React component code alone) and the output is 100% bug-free and performance-regression-free.

**Comment by sebmck** [comment]
Woah, awesome! Thanks for the update @nktpro, really appreciate it. I hadn't had the chance to test this on a large codebase so that's extremely helpful, hopefully soon I'll get a chance to try it on some more exotic codebases to ensure that it's 100% reliable. Thanks again! :blush:
